import React, { useEffect, useState } from 'react';
import { 
  generatePeriodSummaryData, 
  savePeriodReport, 
  getSavedReports, 
  deleteSavedReport 
} from '../services/db';
import { useToast } from '../context/ToastContext';
import { useTheme } from '../context/ThemeContext';
import Modal from '../components/Modal';
import { 
  Calendar, 
  Play, 
  Save, 
  FileDown, 
  Trash2, 
  TrendingUp, 
  ShoppingCart, 
  DollarSign, 
  FolderKanban, 
  History,
  FileCheck,
  FileText
} from 'lucide-react';
import { 
  ResponsiveContainer, 
  AreaChart, 
  Area, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip 
} from 'recharts';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const Reports = () => {
  const { showToast } = useToast();
  const { isDark } = useTheme();

  // Range selectors state
  const [startDate, setStartDate] = useState(() => {
    const d = new Date();
    d.setMonth(d.getMonth() - 2); 
    return d.toISOString().substring(0, 10);
  });
  const [endDate, setEndDate] = useState(() => new Date().toISOString().substring(0, 10));

  // Current compiled report state
  const [compiledReport, setCompiledReport] = useState(null);
  const [compiling, setCompiling] = useState(false);

  // Historic reports list state
  const [savedReports, setSavedReports] = useState([]);
  const [loadingHistory, setLoadingHistory] = useState(true);

  // Save Modal configurations
  const [isSaveModalOpen, setIsSaveModalOpen] = useState(false);
  const [reportTitle, setReportTitle] = useState('');
  const [reportDesc, setReportDesc] = useState('');
  const [saving, setSaving] = useState(false);

  const fetchReportsHistory = () => {
    setLoadingHistory(true);
    try {
      const reports = getSavedReports();
      setSavedReports(reports);
    } catch (error) {
      showToast('Failed to fetch saved reports.', 'error');
    } finally {
      setLoadingHistory(false);
    }
  };

  useEffect(() => {
    fetchReportsHistory();
  }, []);

  // Compile report handler
  const handleCompile = () => {
    if (!startDate || !endDate) {
      showToast('Please specify both start and end date boundaries.', 'warning');
      return;
    }
    if (new Date(startDate) > new Date(endDate)) {
      showToast('Start date cannot succeed End date.', 'error');
      return;
    }

    setCompiling(true);
    try {
      setTimeout(() => {
        const summary = generatePeriodSummaryData(startDate, endDate);
        setCompiledReport(summary);
        showToast('Analytics report compiled successfully.', 'success');
        setCompiling(false);
      }, 300);
    } catch (error) {
      showToast('Failed to compile report.', 'error');
      setCompiling(false);
    }
  };

  // Open Save Dialog helper
  const openSaveDialog = () => {
    if (!compiledReport) return;
    const daysDiff = Math.ceil((new Date(endDate) - new Date(startDate)) / (1000 * 60 * 60 * 24));
    setReportTitle(`Analytics summary: ${daysDiff} days`);
    setReportDesc(`Operational summary compiled between ${startDate} and ${endDate}`);
    setIsSaveModalOpen(true);
  };

  // Save Compiled Report handler
  const handleSaveReport = (e) => {
    e.preventDefault();
    if (!reportTitle) {
      showToast('Please provide a report title.', 'warning');
      return;
    }

    setSaving(true);
    try {
      savePeriodReport(reportTitle, reportDesc, startDate, endDate, compiledReport);
      showToast('Report saved to logs database.', 'success');
      setIsSaveModalOpen(false);
      fetchReportsHistory();
    } catch (error) {
      showToast('Failed to save compiled report.', 'error');
    } finally {
      setSaving(false);
    }
  };

  // Delete saved report handler
  const handleDeleteReport = (id) => {
    if (!window.confirm('Are you sure you want to delete this historical report?')) {
      return;
    }
    try {
      deleteSavedReport(id);
      showToast('Saved report entry deleted.', 'success');
      fetchReportsHistory();
    } catch (error) {
      showToast('Failed to delete report.', 'error');
    }
  };

  // Download PDF compiler helper
  const downloadReportPDF = (report) => {
    try {
      const doc = new jsPDF();
      doc.setFont('helvetica');

      doc.setFontSize(20);
      doc.setTextColor(15, 23, 42); 
      doc.text(report.title, 14, 20);

      doc.setFontSize(10);
      doc.setTextColor(100, 116, 139); 
      doc.text(`Description: ${report.description || 'N/A'}`, 14, 26);
      doc.text(`Covering range: ${report.start_date} to ${report.end_date}`, 14, 31);
      doc.text(`Generated by: ${report.creator_name || 'System'}`, 14, 36);

      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      doc.text("Operational Parameters summary", 14, 46);

      const metricsRows = [
        ["Total Revenue Stream Compiled", `$${parseFloat(report.data_summary.totalRevenue || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
        ["Total Units Sold", (report.data_summary.totalSales || 0).toLocaleString()],
        ["Total Transaction Records Count", (report.data_summary.recordCount || 0).toLocaleString()]
      ];

      autoTable(doc, {
        startY: 50,
        head: [["Performance parameter", "Compiled Metric value"]],
        body: metricsRows,
        theme: 'plain',
        styles: { fontSize: 9.5 }
      });

      if (report.data_summary.categories && report.data_summary.categories.length > 0) {
        doc.text("Category Breakdown Performance", 14, doc.lastAutoTable.finalY + 10);
        
        const catColumns = ["Category", "Units Sold", "Total Revenue"];
        const catRows = report.data_summary.categories.map(c => [
          c.category,
          c.sales,
          `$${parseFloat(c.revenue).toLocaleString()}`
        ]);

        autoTable(doc, {
          startY: doc.lastAutoTable.finalY + 14,
          head: [catColumns],
          body: catRows,
          theme: 'striped',
          headStyles: { fillColor: [79, 70, 229] } 
        });
      }

      doc.save(`compiled_report_${report.id}.pdf`);
      showToast('PDF file downloaded successfully.', 'success');
    } catch (error) {
      showToast('Failed to compile PDF file.', 'error');
    }
  };

  const gridColor = isDark ? '#1F2A45' : '#E2E8F0';
  const labelColor = isDark ? '#94A3B8' : '#64748B';

  return (
    <div className="space-y-8">
      
      <div className="bg-white dark:bg-darkbg-800 p-5 rounded-2xl shadow-sm border border-gray-150 dark:border-darkbg-700">
        <h3 className="text-sm font-bold text-gray-800 dark:text-white mb-4 flex items-center gap-2">
          <Calendar className="h-4.5 w-4.5 text-primary-500" />
          <span>Select Analysis Date Boundaries</span>
        </h3>

        <div className="flex flex-col md:flex-row md:items-end gap-4">
          
          <div className="flex-1">
            <label className="block text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-1.5">
              Start Boundary Date
            </label>
            <input
              type="date"
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
              className="block w-full px-3.5 py-2.5 bg-gray-50 dark:bg-darkbg-900 border border-gray-200 dark:border-darkbg-700 rounded-xl text-sm text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary-500 cursor-pointer"
            />
          </div>

          <div className="flex-1">
            <label className="block text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-1.5">
              End Boundary Date
            </label>
            <input
              type="date"
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
              className="block w-full px-3.5 py-2.5 bg-gray-50 dark:bg-darkbg-900 border border-gray-200 dark:border-darkbg-700 rounded-xl text-sm text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary-500 cursor-pointer"
            />
          </div>

          <button
            onClick={handleCompile}
            disabled={compiling}
            className="flex items-center justify-center gap-1.5 px-6 py-2.5 bg-primary-500 hover:bg-primary-600 rounded-xl text-sm font-bold text-white shadow-md shadow-primary-500/10 transition disabled:opacity-50 h-10 md:h-[42px]"
          >
            {compiling ? (
              <div className="h-4 w-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
            ) : (
              <>
                <Play className="h-4 w-4" />
                <span>Compile Performance</span>
              </>
            )}
          </button>
        </div>
      </div>

      {compiledReport && (
        <div className="space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="text-base font-bold text-gray-900 dark:text-white flex items-center gap-2">
              <FileCheck className="h-5 w-5 text-emerald-500" />
              <span>Compiled Analysis Results</span>
            </h3>
            <button
              onClick={openSaveDialog}
              className="flex items-center gap-1.5 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 rounded-xl text-sm font-bold text-white shadow-md shadow-indigo-600/10 transition"
            >
              <Save className="h-4 w-4" />
              <span>Save Compilation Report</span>
            </button>
          </div>

          <div className="grid grid-cols-1 gap-5 sm:grid-cols-3">
            
            <div className="bg-white dark:bg-darkbg-800 p-5 rounded-2xl border border-gray-150 dark:border-darkbg-700 flex items-start gap-4">
              <div className="p-2.5 rounded-lg text-emerald-500 bg-emerald-500/10">
                <DollarSign className="h-5 w-5" />
              </div>
              <div>
                <p className="text-[10px] font-bold text-gray-450 uppercase">Interval Revenue</p>
                <h4 className="text-lg font-extrabold text-gray-900 dark:text-white mt-1">
                  ${parseFloat(compiledReport.totalRevenue).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                </h4>
              </div>
            </div>

            <div className="bg-white dark:bg-darkbg-800 p-5 rounded-2xl border border-gray-150 dark:border-darkbg-700 flex items-start gap-4">
              <div className="p-2.5 rounded-lg text-violet-500 bg-violet-500/10">
                <ShoppingCart className="h-5 w-5" />
              </div>
              <div>
                <p className="text-[10px] font-bold text-gray-450 uppercase">Interval Units Sold</p>
                <h4 className="text-lg font-extrabold text-gray-900 dark:text-white mt-1">
                  {compiledReport.totalSales.toLocaleString()} units
                </h4>
              </div>
            </div>

            <div className="bg-white dark:bg-darkbg-800 p-5 rounded-2xl border border-gray-150 dark:border-darkbg-700 flex items-start gap-4">
              <div className="p-2.5 rounded-lg text-amber-500 bg-amber-500/10">
                <FolderKanban className="h-5 w-5" />
              </div>
              <div>
                <p className="text-[10px] font-bold text-gray-450 uppercase">Interval Records Evaluated</p>
                <h4 className="text-lg font-extrabold text-gray-900 dark:text-white mt-1">
                  {compiledReport.recordCount} records
                </h4>
              </div>
            </div>

          </div>

          <div className="bg-white dark:bg-darkbg-800 p-5 rounded-2xl shadow-sm border border-gray-150 dark:border-darkbg-700">
            <h4 className="text-xs font-bold text-gray-400 dark:text-gray-500 uppercase mb-4 tracking-wider">Historical daily value logs</h4>
            <div className="h-64">
              {compiledReport.trends.length === 0 ? (
                <div className="flex flex-col items-center justify-center h-full text-gray-400">
                  <p className="text-xs">No daily interval records captured</p>
                </div>
              ) : (
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={compiledReport.trends} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke={gridColor} />
                    <XAxis dataKey="date" stroke={labelColor} fontSize={10} tickLine={false} />
                    <YAxis stroke={labelColor} fontSize={10} tickLine={false} />
                    <Tooltip contentStyle={{ backgroundColor: isDark ? '#151D30' : '#FFFFFF', borderColor: gridColor, borderRadius: '12px' }} />
                    <Area type="monotone" dataKey="revenue" stroke="#4f46e5" fill="#4f46e5" fillOpacity={0.1} name="Daily Revenue ($)" />
                  </AreaChart>
                </ResponsiveContainer>
              )}
            </div>
          </div>

        </div>
      )}

      {/* Historical reports list */}
      <div className="bg-white dark:bg-darkbg-800 rounded-2xl shadow-sm border border-gray-150 dark:border-darkbg-700 overflow-hidden">
        <div className="px-5 py-4 border-b border-gray-150 dark:border-darkbg-700 flex items-center justify-between">
          <h3 className="text-sm font-bold text-gray-800 dark:text-white flex items-center gap-2">
            <History className="h-4.5 w-4.5 text-violet-500" />
            <span>Saved Reports History Archive</span>
          </h3>
          <span className="text-[10px] font-bold text-gray-400 uppercase">Archive logs</span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-gray-150 dark:border-darkbg-700 bg-gray-50/50 dark:bg-darkbg-900/30 text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider">
                <th className="py-3 px-5">Report details</th>
                <th className="py-3 px-5">Range boundaries</th>
                <th className="py-3 px-5">Compiled metrics</th>
                <th className="py-3 px-5">Author</th>
                <th className="py-3 px-5 text-right">Download</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-150 dark:divide-darkbg-700 text-sm">
              {loadingHistory ? (
                [...Array(3)].map((_, i) => (
                  <tr key={i} className="animate-pulse">
                    <td className="py-4 px-5"><div className="h-4 w-40 bg-gray-200 dark:bg-darkbg-700 rounded" /></td>
                    <td className="py-4 px-5"><div className="h-4 w-32 bg-gray-200 dark:bg-darkbg-700 rounded" /></td>
                    <td className="py-4 px-5"><div className="h-4 w-28 bg-gray-200 dark:bg-darkbg-700 rounded" /></td>
                    <td className="py-4 px-5"><div className="h-4 w-20 bg-gray-200 dark:bg-darkbg-700 rounded" /></td>
                    <td className="py-4 px-5"><div className="h-4 w-12 bg-gray-200 dark:bg-darkbg-700 rounded ml-auto" /></td>
                  </tr>
                ))
              ) : savedReports.length === 0 ? (
                <tr>
                  <td colSpan="5" className="py-8 text-center text-gray-450 text-xs font-semibold">
                    No historical reports found. Compile and save one above!
                  </td>
                </tr>
              ) : (
                savedReports.map((report) => (
                  <tr key={report.id} className="hover:bg-gray-50/50 dark:hover:bg-darkbg-900/20 text-gray-800 dark:text-gray-200 transition-colors">
                    <td className="py-3 px-5">
                      <div className="flex items-start gap-2.5">
                        <FileText className="h-5 w-5 text-primary-500 shrink-0 mt-0.5" />
                        <div>
                          <p className="font-semibold text-sm">{report.title}</p>
                          <p className="text-xs text-gray-400 dark:text-gray-550 mt-0.5">{report.description || 'No description provided.'}</p>
                        </div>
                      </div>
                    </td>
                    <td className="py-3 px-5 font-mono text-xs whitespace-nowrap">
                      {report.start_date} to {report.end_date}
                    </td>
                    <td className="py-3 px-5 text-xs text-gray-600 dark:text-gray-400">
                      <div className="space-y-0.5 font-medium">
                        <p>Revenue: <span className="font-bold text-gray-850 dark:text-gray-200">${parseFloat(report.data_summary.totalRevenue || 0).toLocaleString()}</span></p>
                        <p>Sales: <span className="font-bold text-gray-850 dark:text-gray-200">{(report.data_summary.totalSales || 0).toLocaleString()} units</span></p>
                      </div>
                    </td>
                    <td className="py-3 px-5">
                      <span className="text-xs px-2 py-0.5 bg-gray-100 dark:bg-darkbg-700 rounded-lg text-gray-600 dark:text-gray-300 font-medium">
                        {report.creator_name || 'System'}
                      </span>
                    </td>
                    <td className="py-3 px-5 text-right">
                      <div className="flex items-center justify-end gap-1.5">
                        <button
                          onClick={() => downloadReportPDF(report)}
                          className="p-1.5 text-gray-400 hover:bg-gray-100 hover:text-primary-500 dark:hover:bg-darkbg-700 dark:hover:text-primary-400 rounded-lg transition"
                          title="Download PDF"
                        >
                          <FileDown className="h-4.5 w-4.5" />
                        </button>
                        <button
                          onClick={() => handleDeleteReport(report.id)}
                          className="p-1.5 text-gray-400 hover:bg-gray-100 hover:text-rose-500 dark:hover:bg-darkbg-700 dark:hover:text-rose-450 rounded-lg transition"
                          title="Delete Report File"
                        >
                          <Trash2 className="h-4.5 w-4.5" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Save Modal */}
      <Modal isOpen={isSaveModalOpen} onClose={() => setIsSaveModalOpen(false)} title="Confirm Save Parameters">
        <form onSubmit={handleSaveReport} className="space-y-4">
          
          <div>
            <label className="block text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-1.5">
              Report Title
            </label>
            <input
              type="text"
              required
              value={reportTitle}
              onChange={(e) => setReportTitle(e.target.value)}
              placeholder="E.g. Q1 Sales Performance Summary"
              className="block w-full px-3.5 py-2.5 bg-gray-50 dark:bg-darkbg-900 border border-gray-200 dark:border-darkbg-700 rounded-xl text-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent text-gray-900 dark:text-white transition"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-1.5">
              Description / Notes
            </label>
            <textarea
              rows="3"
              value={reportDesc}
              onChange={(e) => setReportDesc(e.target.value)}
              placeholder="Optional summary note context..."
              className="block w-full px-3.5 py-2.5 bg-gray-50 dark:bg-darkbg-900 border border-gray-200 dark:border-darkbg-700 rounded-xl text-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent text-gray-900 dark:text-white transition resize-none"
            />
          </div>

          <div className="flex items-center justify-end gap-3 pt-4 border-t border-gray-150 dark:border-darkbg-700">
            <button
              type="button"
              onClick={() => setIsSaveModalOpen(false)}
              className="px-4 py-2 border border-gray-200 dark:border-darkbg-700 bg-white dark:bg-darkbg-850 hover:bg-gray-55 rounded-xl text-sm font-semibold text-gray-505 dark:text-gray-200 transition"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={saving}
              className="px-4 py-2 bg-indigo-650 hover:bg-indigo-700 rounded-xl text-sm font-bold text-white transition disabled:opacity-50 flex items-center gap-1.5 shadow-md shadow-indigo-600/10"
            >
              {saving ? (
                <div className="h-4 w-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
              ) : (
                <>
                  <Save className="h-4 w-4" />
                  <span>Confirm Save</span>
                </>
              )}
            </button>
          </div>

        </form>
      </Modal>

    </div>
  );
};

export default Reports;
